### ISSUE TITLE
Feature Request: 1.19.3

### ISSUE THREAD

**Issue by EntangledLabs** [Stardust-Labs-MC/Continents#1]
I really love this mod! Unfortunately, it does not appear to work on 1.19.3 - can we get a version port?

**Comment by catter1** [comment]
This already works just fine on 1.19.3.

**Comment by catter1** [comment]
I don't know what "doesn't seem to work" means. Here's what I'd recommend to do to see if it's working:

- Go to [jacobsjo's datapack map](https://map.jacobsjo.eu/) web app, and put Continents in.
- Enter the seed your using, and view the map. See if the map looks the same in your world.
- If it does, great!

Just remember that adding Continents is not a very obvious change to your world.
