### ISSUE TITLE
Config [Enhancement]

### ISSUE THREAD

**Issue by taimur-git** [Stardust-Labs-MC/Continents#2]
### Describe your enhancement/improvement, with context and reasoning.

A config menu that could change the size of continents, or frequency of continents.

**Comment by catter1** [comment]
Datapacks cannot have configs, unfortunately. This is out of our scope.

However, if you're interested, I have attached below a guide from our Discord bot on how to how to adjust the *size* of continents. If you are curious on how to do other more adjustments (some may be easier than others, and some very difficult), feel free to ask in our [Discord server](www.discord.gg/stardustlabs).

Unzip Continents and open the `Continents/data/minecraft/worldgen/density_function/overworld/` folder.
• Open `base_continents.json`. You should see this:
```
{
    "type": "add",
    "argument1":{
        "argument": {
            "xz_scale": 0.13,
            "y_scale": 0.0,
            "noise": "minecraft:continentalness",
            "shift_x": "minecraft:shift_x",
            "shift_y": 0.0,
            "shift_z": "minecraft:shift_z",
            "type": "minecraft:shifted_noise"
        },
        "type": "minecraft:flat_cache"
    },
    "argument2":"continents:continent_bias"
}
```
• To increase the continent sizes, lower the `xz_scale` value. Halving = 4x larger continents.
• To decrease the continent sizes, raise the `xz_scale` value. Doubling = 4x smaller continents.
• Do not change anything else!
• Zip it up and enjoy! Keep in mind that this has __zero__ impact on the spawn island.
