### ISSUE TITLE
World Type Button Compatibility [Mod Version] [Enhancement]

### ISSUE THREAD

**Issue by Wionsito** [Stardust-Labs-MC/Continents#3]
### Describe your enhancement/improvement, with context and reasoning.

Add a way to use continents world generation using the world type button that appears when you're creating a new world.

**Comment by catter1** [comment]
Continents is a datapack, and therefore is unfortunately not possible.

**Comment by Wionsito** [comment]
> Continents is a datapack, and therefore is unfortunately not possible.

But I'm talking about the mod version available on Modrinth.

**Comment by catter1** [comment]
The mod version is just the datapack version packaged as a mod

**Comment by Wionsito** [comment]
> The mod version is just the datapack version packaged as a mod

Well, if that isn't possible, at least a way to disable it, so isn't used on new worlds while disabled?

**Comment by catter1** [comment]
With the mod, unfortunately not. If you do want this capability, you may be interested in just using the datapack version. It would mean you need to individually add it to every world you want it in, but it would give the control you are looking for. This also applies to Terralith, if not already clear.

I suppose I should also clarify a bit on the "unfortunately not possible" bit of my oririginal response. This *is* technically possible (for both mods), but it's simply not practical for us. Not only would it take quite a lot of refactoring, but it risks having incompatibility issues with other worldgen mods that also use World Types to enable their generation. The only other somewhat reasonable suggestion I can think of at the moment that would be similar: have a *separate* button in the world creation menu to disable each mods' generation. I am not sure how complex this would be, but I can add this (or any other solution I can think of) to our to-do list. Do keep in mind that if I find this possible, it would be low piority.

**Comment by Wionsito** [comment]
> With the mod, unfortunately not. If you do want this capability, you may be interested in just using the datapack version. It would mean you need to individually add it to every world you want it in, but it would give the control you are looking for. This also applies to Terralith, if not already clear.
> 
> I suppose I should also clarify a bit on the "unfortunately not possible" bit of my oririginal response. This _is_ technically possible (for both mods), but it's simply not practical for us. Not only would it take quite a lot of refactoring, but it risks having incompatibility issues with other worldgen mods that also use World Types to enable their generation. The only other somewhat reasonable suggestion I can think of at the moment that would be similar: have a _separate_ button in the world creation menu to disable each mods' generation. I am not sure how complex this would be, but I can add this (or any other solution I can think of) to our to-do list. Do keep in mind that if I find this possible, it would be low piority.

Thanks a lot for your help, well if that was possible even if it is low priority, I would like that imo that would be more practical instead of adding the data pack individually, but I will use that solution at least right now. 

Edit: btw, if it happens, could you notify me? (if you want, obviously)
