### ISSUE TITLE
[Enhancement] Datapacks to Adjust Continent Sizing/Spacing

### ISSUE THREAD

**Issue by AngellusMortis** [Stardust-Labs-MC/Continents#4]
### Describe your enhancement/improvement, with context and reasoning.

So if my poking around the datapack provided is correct, it looks like the size of the continents and everything can be adjusted. It would be awesome if there was some "official" datapacks for some presets to help with setup. 

I really love the mod and the idea of having concrete sized landmasses, but I want there to be more land and less ocean then the default worldgen. 

Here is my world (~7k radius) on 1.20.1 with Terralith + Tectonic + Continents + Terrablender + Biomes o' Plenty + Regions Unexplored
![image](https://github.com/Stardust-Labs-MC/Continents/assets/490848/204cf150-5065-4b60-9fb5-df46d609dd5e)

**Comment by catter1** [comment]
We do provide guides in the Stardust Labs discord on how to adjust the size yourself (see below). However, we do not have plans to have multiple versions of our packs readily available for people to choose what they want. This would be way too much upkeep for us, and could cause confusion, especially when users have to update and download the wrong version.

![image](https://github.com/Stardust-Labs-MC/Continents/assets/63272345/d520f41c-af13-4fdf-ab97-2bfad4cfd2c8)

**Comment by AngellusMortis** [comment]
That information is really great, thanks! It is really nice that is it a lot simpler than I thought. Is there any chance of actually updating the [Continents](https://stardustlabs.miraheze.org/wiki/Continents) wiki so people do not need to join yetAnotherDiscordServer? It seems like everyone community is trying to force you into a Discord server just so you can see content. I have like 30 servers just permanently muted.

**Comment by catter1** [comment]
Don't worry, I completely understand the Discord server argument. It's easy for me to put all the resources in Discord, but not everyone can or wants to join servers to ask questions and get information. I don't want to put this information on the wiki, since it is unofficial and unsupported. However, I do have plans to get all the info, FAQ, and unofficial configs off of Discord and onto a website in the future.

**Comment by AngellusMortis** [comment]
Oh, I did not realize the wiki was unofficial. My mistake.
