### ISSUE TITLE
[Bug] 1.20.1 Broken

### ISSUE THREAD

**Issue by Krimatoria** [Stardust-Labs-MC/Continents#6]
### What Minecraft version(s) does this apply to?

1.20 - 1.20.1

### Project version

Continents_1.20.x_v1.1.5.jar

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

I don't even have any islands with one mod, it just doesn't work. An ordinary, generally unified world is always generated.

**Comment by catter1** [comment]
Can you use a minimap or other similar mod to see it from above? Itś not always easy to see if Continents is working.

**Comment by Krimatoria** [comment]
> Can you use a minimap or other similar mod to see it from above? Itś not always easy to see if Continents is working.

I've already tried, but judging by the screenshot and the examples with this mod that I've seen, I don't have anything like this) but I'll create a new world with a map today or tomorrow to check it out again.

**Comment by dberghoff** [comment]
I'm having the same issue. It appears to be a conflict with the latest version of Tectonic (2.4.1). The previous version of Tectonic on mc1.20.1, which is 2.3.5b, works fine with Continents.

**Comment by catter1** [comment]
Thanks for your comment. I have had other people asking aobut this recently as well, so I will keep it in mind. Will see if Author can replicate the issue.
